source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'Example' do
  pod 'AttributedStringStyle', :path => '../'

  target 'ExampleTests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2'
    pod 'Nimble', '~> 8.0'
  end
end
